### ISSUE TITLE
How to split fromName to firstName and lastName

### ISSUE THREAD

**Issue by daituzhang** [craftcms/contact-form#155]
Hi thank you for this awesome plugin!
Is it possible to split the fromName to firstName and lastName?

Thank you.

**Comment by emarthinsen** [comment]
Sure. You would just do something like this:

```
<label for="first-name">First Name</label>
<input id="first-name" type="text" name="message[FirstName]" value="">

<label for="last-name">Last Name</label>
<input id="last-name" type="text" name="message[LastName]" value="">
```

**Comment by bertoost** [comment]
@emarthinsen and how does contact-form know what would be the contents of `fromName` field? since that one is required

**Comment by emarthinsen** [comment]
@bertoost Good question. It's been a while since I was in this code, but I'd probably create a hidden form field for `fromName` and set it to something arbitrary. Or, just capture the first name in the `fromName` field and add a custom field for the last name. This is probably the route I would go. If you want to validate the last name, there's an `afterValidate` method that you can hook into. The docs show an example of making a custom field required.

**Comment by bertoost** [comment]
Yeah I have now done that too. Except for the `afterValidate` .. good one! thanks
