### ISSUE TITLE
Flash messages and errors not working

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/contact-form#172]
I can send the form without filling any field.
Shouldn't there be error messages?

Also adding:
```
{% if craft.app.session.hasFlash('notice') %}
    <p class="message notice">{{ craft.app.session.getFlash('notice') }}</p>
{% elseif craft.app.session.hasFlash('error') %}
    <p class="message error">{{ craft.app.session.getFlash('error') }}</p>
{% endif %}
```
under the form shows nothing.

I guess i have to remove:
```
<input type="hidden" name="action" value="contact-form/send">
{{ redirectInput('about/about_thanks') }}
```
to make the flash message work. But it does not.

**Comment by amityweb** [comment]
I have also discovered this issue.

At first I thought it was due to a plugin we used, Contact Form Extension, that adds Google ReCaptcha. If there was a problem with the ReCaptcha (e.g. two forms on one page caused us an issue), the email wont send because it fails captcha, BUT we still had the successFlashMessage. 

I have removed the ReCaptcha and addd the honeypot plugin by Craft. If I fill in the honeypot field the email is not sent, BUT I still get the successFlashMessage. 

So I am led to believe its an issue with this plugin. 

Its a serious issue as we have less enquiries on our new Craft site which is identical to the old one, and one of the reasons could be people making mistakes on contact forms and so the email is not sent, but they think its sent as they see the successFlashMessage

**Comment by notorigine** [comment]
Anything new on this issue? This is pretty bad...

**Comment by angrybrad** [comment]
I'm not able to reproduce this using the example code from the docs:

```
{% macro errorList(errors) %}
{% if errors %}
<ul class="errors">
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

{% from _self import errorList %}

{% if craft.app.session.hasFlash('notice') %}
    <p class="message notice">{{ craft.app.session.getFlash('notice') }}</p>
{% elseif craft.app.session.hasFlash('error') %}
    <p class="message error">{{ craft.app.session.getFlash('error') }}</p>
{% endif %}

<form method="post" action="" accept-charset="UTF-8">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="contact-form/send">
    {{ redirectInput('contact/thanks') }}

    <h3><label for="from-name">Your Name</label></h3>
    <input id="from-name" type="text" name="fromName" value="{{ message.fromName ?? '' }}">
    {{ message is defined and message ? errorList(message.getErrors('fromName')) }}

    <h3><label for="from-email">Your Email</label></h3>
    <input id="from-email" type="email" name="fromEmail" value="{{ message.fromEmail ?? '' }}">
    {{ message is defined and message ? errorList(message.getErrors('fromEmail')) }}

    <h3><label for="subject">Subject</label></h3>
    <input id="subject" type="text" name="subject" value="{{ message.subject ?? '' }}">
    {{ message is defined and message ? errorList(message.getErrors('subject')) }}

    <h3><label for="message">Message</label></h3>
    <textarea rows="10" cols="40" id="message" name="message">{{ message.message ?? '' }}</textarea>
    {{ message is defined and message ? errorList(message.getErrors('message')) }}

    <input type="submit" value="Send">
</form>
```

Clicking send without filling in anything properly fails validation and the flash error message displays properly.

![Screen Shot 2020-01-02 at 12 52 02 PM](https://user-images.githubusercontent.com/61869/71692430-b11f0f80-2d5e-11ea-8827-42028295ff75.png)

**Comment by JonQuayle** [comment]
I know this was closed but I just had the same issue and figured it out, hopefully this helps anyone who might get this issue again. Turned out, for me, it was the 'required' tag being added to the input. For some reason it was blocking anything set as a flash message or custom error message. Removing those brought the errors back.
