### ISSUE TITLE
Contact Form Returns successFlashMessage if isSpam is true

### ISSUE THREAD

**Issue by amityweb** [craftcms/contact-form#175]
I am using Craft's Honeypot plugin, and I also tried Contact Form Extension's Google ReCaptcha. In both cases, if the honeypot or recaptcha does not validate, the successFlashMessage is still returned.

This gives a real user false expectation that their message was sent. 

A real user can trigger the honeypot if using a browser extension to quick fill in fields... I use one.

In this case users need to be informed the message was not sent so they can try manually but I cannot see how if the successFlashMessage is returned.

**Comment by amityweb** [comment]
Just curious if someone is able to help with this, I think its very important to fix, because the site is having less enquiries and so a drop in sales switching to Craft, and I believe it because real people are identified as spam but not informed of this, so they believe their enquiry is sent so dont have an opportunity to try to fix it. We would need to show an error message if the form is not sent. ANY time a form is not sent an error needs to show, I dont think there is any reason to justify showing a success message unless the email is actually sent. Thanks

**Comment by olivierbon** [comment]
@amityweb I'm not able to replicate this. If I populate the honeypot field and try to send the message, I get `There was a problem with your submission, please check the form and try again!`.

Could you double check your implementation please?

**Comment by amityweb** [comment]
Hi oli. Ok thats good to know! I will have another look. I looked before but cant really see what we could be doing to override this. We use Contact Form Extentions plugin to save the details, maybe something in that plugin is breaking it. Otherwise its just your plugin and then we check for flash messages and output them, and outputting the success message. At least I know it is supposed to work OK, so thanks.

**Comment by angrybrad** [comment]
> Contact Form Returns successFlashMessage if isSpam is true

The whole point of isSpam is if whatever method is being used determines the email is SPAM, then we want to _not_ send the email, but let the bot/script/end-user think the email _was_ sent.

> A real user can trigger the honeypot if using a browser extension to quick fill in fields... I use one.

I'm not sure how that's possible... it's not like the browser can autofill the honeypot hidden input field.

**Comment by amityweb** [comment]
> but let the bot/script/end-user think the email was sent.
I disagree about that, and not sure automated bots would even know if its sent or not based on a message. I really dont care if a spam bot even does know its not sent. 

The problem is real users can and are identified as spam, and they think their enquiry is sent. Normally, and as is the case in all other systems I use, a message tells the user its spam so they can remedy that or contact the company a different way. 

The craft method results in lost emails and lost sales, which is very very bad. If you really want to tell the user its sent, then we need an option to override it so we can decide to tell the user its not sent. 

About the honeypot... I use a chrome plugin to autofill details, and it can fill in all fields with some random data, but thinking about it further, I think its very rare as its a special plugin that is intended to fill in all fields, and not only fill in known fields, so this is not such a big issue actually. The big issue is real users thinking their messages are sent but they are not. 

Thanks

**Comment by amityweb** [comment]
Just to add to this, the issue is mainly when using Google ReCaptcha, and when Google identifies the real user as spam. We use the honeypot method now, so users are not wrongly identified as spam, but the customer still gets loads of spam, so we want to revert back to ReCaptcha but we cant until this issue is fixed, because there will be lost enquiries due to the wrong flash message. 
Thanks

**Comment by angrybrad** [comment]
The whole point of that `isSpam` feature is to prevent the email from being sent.  If that's not the behavior you want, you should stop using plugins that set it and let Google/Gmail deal with filtering spam directly or send an FR/PR to the ReCaptcha plugin to make setting `$event->isSpam => true` optional.

**Comment by amityweb** [comment]
`The whole point of that isSpam feature is to prevent the email from being sent.`
Yes it does this. The issue is a real user identified as spam is not informed, they are told their email is sent which is wrong. We do not want this behaviour. This is a personal preference by you which we should not have to adopt. If you want this you need to give us an override. 

> you should stop using plugins that set it and let Google/Gmail deal with filtering spam directly
are you making an assumption we use Google for email? We do not use Google for email and will not be switching to Google either. 

`or send an FR/PR to the ReCaptcha plugin to make setting $event->isSpam => true optional.`
but Oli did it and you reverted it

The main reason we switched to Craft is because of its customisability and ability to develop it how we want it so I am very surprised a personal opinion is forced upon us. I would be happy to add something in my custom plugin to override this setting if possible, it does need to be overridden, we cannot inform real users their email is sent when it is not, its very bad.

**Comment by angrybrad** [comment]
> but Oli did it and you reverted it

Because it changed the behavior of the plugin in a non-backward compatible way.  I suggested making a PR to the ReCaptcha plugin (not Contact Form) so that setting `$event->isSpam => true` is optional, which would solve your problem.

> We do not use Google for email and will not be switching to Google either.

Cool.

> The issue is a real user identified as spam is not informed the email is not sent, they are told via the flash message that their email is sent which is wrong. We do not want this behaviour.

Fair. FWIW, this has been the default behavior since 2014 and this is the first time it's been brought up.

> The main reason we switched to Craft is because of its customisability and ability to develop it how we want it so I am very surprised this setting is forced upon us,

Happy to accept a PR that adds the ability to set the successful flash message in the case of detected SPAM to something customizable in the plugin settings that doesn't break backwards compatibility.

Or if you'd like to create another issue for this as a feature request, then we can look into implementing it as our resources will allow.

In the meantime, if this is a critical issue for you, you have other options besides making a PR to the ReCaptcha plugin.

1. You can fork either Contact Form or Recaptcha to create a custom local plugin that does whatever logic you require: https://docs.craftcms.com/v3/extend/plugin-guide.html

2. You can check out any of the other free and commercial form-based plugins that are available and are much more full-featured in regards to both forms and SPAM prevention.  https://plugins.craftcms.com/categories/forms

**Comment by amityweb** [comment]
Unbelievable to be honest. I have emailed you an example missed enquiry from the customer. In one web.log we have 4 real enquiries. I dont understand why you think its acceptable. I will try alternate forms and maybe have to revert back to Google ReCaptcha 2 and then highly recommend no one uses Craft's contact form due to missed sales enquiries.

**Comment by amityweb** [comment]
We have reverted backward to Google ReCaptcha V2 with Challenge, so now a user can verify they are human and so hopefully no missed emails anymore compared to invisible ReCaptcha with Craft.

**Comment by MattWilcox** [comment]
We've been bitten by this "recaptcha rejects, Craft says it sent" behaviour, and wasted days trying to fix the issue of "lost genuine enquiries" on a technical level. We'd have saved a ton of time if the person completing the form had been able to see they were flagged as spam, instead of a lie.

> The whole point of isSpam is if whatever method is being used determines the email is SPAM, then we want to not send the email, but let the bot/script/end-user think the email was sent.

Except you're assuming RECAPTCHA is always right. Showing a success message to a person after a failed recaptcha test is factually wrong, and it costs people money and goodwill. If that lines up with what it's always done, it's always been wrong. Its a silent bad behaviour, and the assumption that only a bot will ever enter this bit of logic is wrong.

Adding the voice here as a paper trail, considering `this has been the default behavior since 2014 and this is the first time it's been brought up`. Here's two people bringing it up.

**Comment by amityweb** [comment]
I find Googles auto captchas lead to false positives, so we still use V2 checkbox on all our websites, not just Craft, its not worth the risk losing sales. There will be more people they just haven't noticed as they wont get some emails.
