### ISSUE TITLE
Reply-To does not work with Gmail

### ISSUE THREAD

**Issue by groe** [craftcms/contact-form#67]
Unfortunately Gmail ignores the `Reply-To` email header if the `From` address is the same as the `To` address (or is configured as a "Send as..."-Account in the Gmail settings), as it is the case with the ContactForm plugin.

So if you receive an email from the plugin in gmail and click Reply, it fills in your own address in the `To` field of the reply, and not the address of the person submitting the form.

This could be fixed by adding a config setting "From Email" and configuring it with something like `noreply@my.tld`.

**Comment by NathanHeffley** [comment]
I'm having this problem even when the email it's sending from is different from the email I receive it in (I send from email@website.com to personal@gmail.com for example).

I put in pull request #97 if you want to check it out. It just adds an option to put all the data (name, email and subject) into the main email body, that way you don't lose any data due to stuff like sending the email to a Gmail account.

**Comment by brandonkelly** [comment]
The `From` email is just whatever your System Email Address is set to in Settings → Email, so you can set that to `noreply@my.tld` to work around this.
